ReservedWord		1		1		continue		
ReservedWord		2		1		do		
ReservedWord		3		1		sizeof		
ReservedWord		4		1		else		
ReservedWord		5		1		for		
ReservedWord		6		1		if		
ReservedWord		7		1		int		
ReservedWord		8		1		return		
ReservedWord		9		1		struct		
ReservedWord		10		1		break		
ReservedWord		11		1		typedef		
ReservedWord		12		1		void		
ReservedWord		13		1		while		
ReservedWord		14		1		char		
