a
[
         f
         (
               a
            +
               b
         )
      -
         sqrt
         (
               f
               (
                  a
               )
               [
                  i
               ]
            +
               f
               (
                  foo
                  (
                  )
                  (
                     a
                     [
                              i
                           +
                              1
                        +
                           f
                           (
                              a
                              [
                                 f
                                 (
                                    a
                                    [
                                       f
                                       (
                                       )
                                    ]
                                 )
                              ]
                           )
                     ]
                  )
               )
         )
   +
      a
]
